# Generated by Django 4.2.7 on 2025-08-19 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoho_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('deal_name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('account_id', models.CharField(blank=True, max_length=255, null=True)),
                ('account_name', models.CharField(blank=True, max_length=255, null=True)),
                ('stage', models.CharField(blank=True, max_length=255, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('created_time', models.DateTimeField(blank=True, null=True)),
                ('modified_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='is_dnc',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='synctracker',
            name='entity_type',
            field=models.CharField(choices=[('contacts', 'Contacts'), ('accounts', 'Accounts'), ('intern_roles', 'Intern Roles'), ('deals', 'Deals')], max_length=50, unique=True),
        ),
    ]
