# Generated by Django 4.2.7 on 2025-08-19 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoho_app', '0002_deal_account_is_dnc_alter_synctracker_entity_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactDeal',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('deal_name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('contact_id', models.CharField(blank=True, max_length=255, null=True)),
                ('account_id', models.CharField(blank=True, max_length=255, null=True)),
                ('account_name', models.CharField(blank=True, max_length=255, null=True)),
                ('stage', models.CharField(blank=True, max_length=255, null=True)),
                ('deal_type', models.CharField(blank=True, max_length=255, null=True)),
                ('closing_date', models.DateTimeField(blank=True, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('created_time', models.DateTimeField(blank=True, null=True)),
                ('modified_time', models.DateTimeField(blank=True, null=True)),
                ('created_by_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_by_name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_by_email', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
