# Generated by Django 4.2.7 on 2025-08-21 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoho_app', '0003_contactdeal'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleDealSync',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intern_role_id', models.CharField(max_length=255, unique=True)),
                ('total_rejected_deals', models.IntegerField(default=0)),
                ('last_sync_date', models.DateField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
