# Generated by Django 5.2.4 on 2025-08-25 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoho_app', '0004_roledealsync'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactDeal',
        ),
        migrations.AddField(
            model_name='contact',
            name='partnership_specialist_email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='partnership_specialist_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
