# Generated by Django 4.2.7 on 2025-08-25 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoho_app', '0005_add_partnership_specialist_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='partnership_specialist_email',
        ),
        migrations.AlterField(
            model_name='synctracker',
            name='entity_type',
            field=models.CharField(choices=[('contacts', 'Contacts'), ('accounts', 'Accounts'), ('intern_roles', 'Intern Roles'), ('deals', 'Deals'), ('role_deals', 'Role Deals')], max_length=50, unique=True),
        ),
    ]
