# Generated by Django 4.2.7 on 2025-08-26 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zoho_app', '0006_remove_contact_partnership_specialist_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLimiter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.CharField(max_length=255, unique=True)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_email_date', models.DateTimeField()),
                ('emails_sent_this_week', models.IntegerField(default=0)),
                ('week_start_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OutreachLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intern_role_id', models.CharField(max_length=255)),
                ('role_title', models.CharField(blank=True, max_length=255, null=True)),
                ('company_id', models.CharField(blank=True, max_length=255, null=True)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('subject', models.CharField(max_length=500)),
                ('email_type', models.CharField(default='initial', max_length=50)),
                ('sender_email', models.CharField(max_length=255)),
                ('sender_name', models.CharField(blank=True, max_length=255, null=True)),
                ('recipients', models.TextField()),
                ('candidate_ids', models.TextField()),
                ('candidates_count', models.IntegerField(default=0)),
                ('is_urgent', models.BooleanField(default=False)),
                ('is_sent', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('follow_up_count', models.IntegerField(default=0)),
                ('last_follow_up_date', models.DateTimeField(blank=True, null=True)),
                ('next_follow_up_date', models.DateTimeField(blank=True, null=True)),
                ('response_received', models.BooleanField(default=False)),
                ('response_date', models.DateTimeField(blank=True, null=True)),
                ('response_type', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FollowUpTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follow_up_type', models.CharField(max_length=50)),
                ('scheduled_date', models.DateTimeField()),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('outreach_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_ups', to='zoho_app.outreachlog')),
            ],
            options={
                'ordering': ['scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='CandidateOutreachHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_id', models.CharField(max_length=255)),
                ('intern_role_id', models.CharField(max_length=255)),
                ('cycle_number', models.IntegerField(default=1)),
                ('initial_outreach_date', models.DateTimeField()),
                ('last_follow_up_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='active', max_length=50)),
                ('response_received', models.BooleanField(default=False)),
                ('response_date', models.DateTimeField(blank=True, null=True)),
                ('response_type', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('outreach_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_history', to='zoho_app.outreachlog')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('contact_id', 'intern_role_id', 'cycle_number')},
            },
        ),
    ]
