# Generated by Django 4.2.7 on 2025-08-28 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zoho_app', '0007_emaillimiter_outreachlog_followuptask_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='outreachlog',
            name='in_reply_to',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='outreachlog',
            name='message_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='outreachlog',
            name='parent_outreach_log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='follow_up_emails', to='zoho_app.outreachlog'),
        ),
        migrations.AddField(
            model_name='outreachlog',
            name='thread_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
