# Generated by custom patch
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('zoho_app', '0008_add_message_tracking_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='placement_automation',
            field=models.CharField(max_length=255, null=True, blank=True),
        ),
    ]
