# Generated by Django 5.2.4 on 2025-09-11 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoho_app', '0009_add_placement_automation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobmatch',
            old_name='matched_industries',
            new_name='matched_industry_1',
        ),
        migrations.AddField(
            model_name='jobmatch',
            name='industry_1_match',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobmatch',
            name='industry_2_match',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobmatch',
            name='matched_industry_2',
            field=models.TextField(blank=True, null=True),
        ),
    ]
